In [14]:
import sys
sys.path.insert(0,"../")
from DecisionTree import DecisionTreeClassifier

In [13]:
%load_ext autoreload
%autoreload 2

In [4]:
import pandas as pd
import numpy as np

In [5]:
from sklearn import datasets
from sklearn.model_selection import train_test_split

iris=datasets.load_iris()
X,y=iris.data,iris.target
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=1234)

In [47]:
trees = []
from DecisionTree import DecisionTreeClassifier

tree = DecisionTreeClassifier(max_depth=20)

def fit(X,y):
    X,y = pd.DataFrame(X),pd.Series(y)
    print(type(X),type(y))

    X['Target'] = y
    #print(X.head())

    #Create a bootstrapped dataset
    X = X.sample(n=len(X),replace=True)

    target = X['Target']
    X = X.drop('Target',axis=1)

    #Set a feature size to select from dataset.
    #feature_size = round(np.sqrt(X.shape[1]))

    #Randomly select features from dataset
    #random_features_df = X.sample(n=feature_size,axis="columns")

    #print(type(random_features_df))

    #reset column names for random DataFrame
    #random_features_df.columns = range(random_features_df.shape[1])

    #Convert df back to np array
    #random_features_np = random_features_df.to_numpy()
    #target = target.to_numpy()
    X = X.to_numpy()
    target = target.to_numpy()

    #Create a decision tree for this data
    root = tree._build_decision_tree(X,target)

    if root is not None:
        trees.append(root)
    else:
        print("root was not built properly")

for _ in range(20):
    fit(X_train, y_train)
print(trees)

<class 'pandas.core.frame.DataFrame'> <class 'pandas.core.series.Series'>
<class 'pandas.core.frame.DataFrame'> <class 'pandas.core.series.Series'>
<class 'pandas.core.frame.DataFrame'> <class 'pandas.core.series.Series'>
<class 'pandas.core.frame.DataFrame'> <class 'pandas.core.series.Series'>
<class 'pandas.core.frame.DataFrame'> <class 'pandas.core.series.Series'>
<class 'pandas.core.frame.DataFrame'> <class 'pandas.core.series.Series'>
<class 'pandas.core.frame.DataFrame'> <class 'pandas.core.series.Series'>
<class 'pandas.core.frame.DataFrame'> <class 'pandas.core.series.Series'>
<class 'pandas.core.frame.DataFrame'> <class 'pandas.core.series.Series'>
<class 'pandas.core.frame.DataFrame'> <class 'pandas.core.series.Series'>
<class 'pandas.core.frame.DataFrame'> <class 'pandas.core.series.Series'>
<class 'pandas.core.frame.DataFrame'> <class 'pandas.core.series.Series'>
<class 'pandas.core.frame.DataFrame'> <class 'pandas.core.series.Series'>
<class 'pandas.core.frame.DataFrame'> 

In [45]:
print(len(X_test))

45


In [53]:
prediction = []
predictions=[]
for x in X_test:
    for root in trees:
        prediction.append(tree._traverse_decision_tree(x,root))
    predictions.append(max(set(prediction),key=prediction.count))
    prediction.clear()

#print(len(predictions[1]))
predictions = np.array(predictions)
print(len(predictions))
acc=np.sum(predictions==y_test)/len(y_test)
print(acc)


45
0.9777777777777777


In [38]:
for x in X_test:
    print(x)

[6.1 3.  4.6 1.4]
[6.1 2.9 4.7 1.4]
[6.3 2.9 5.6 1.8]
[4.6 3.4 1.4 0.3]
[5.2 2.7 3.9 1.4]
[4.7 3.2 1.6 0.2]
[5.2 3.5 1.5 0.2]
[5.  3.2 1.2 0.2]
[5.7 2.8 4.1 1.3]
[7.7 2.8 6.7 2. ]
[5.8 2.7 3.9 1.2]
[4.4 3.2 1.3 0.2]
[7.7 3.8 6.7 2.2]
[5.9 3.  4.2 1.5]
[5.  3.5 1.6 0.6]
[5.7 2.6 3.5 1. ]
[6.3 3.3 6.  2.5]
[5.  3.  1.6 0.2]
[6.7 2.5 5.8 1.8]
[5.6 2.7 4.2 1.3]
[6.4 2.9 4.3 1.3]
[6.5 2.8 4.6 1.5]
[6.4 3.2 4.5 1.5]
[6.1 2.8 4.7 1.2]
[7.2 3.6 6.1 2.5]
[5.3 3.7 1.5 0.2]
[6.3 2.7 4.9 1.8]
[5.8 2.6 4.  1.2]
[7.1 3.  5.9 2.1]
[4.8 3.4 1.6 0.2]
[5.1 2.5 3.  1.1]
[6.2 2.8 4.8 1.8]
[5.  3.5 1.3 0.3]
[6.3 2.8 5.1 1.5]
[6.7 3.  5.  1.7]
[4.8 3.4 1.9 0.2]
[4.4 2.9 1.4 0.2]
[5.4 3.4 1.7 0.2]
[4.6 3.6 1.  0.2]
[5.  2.3 3.3 1. ]
[5.5 3.5 1.3 0.2]
[6.2 2.2 4.5 1.5]
[5.2 4.1 1.5 0.1]
[6.9 3.1 5.1 2.3]
[7.2 3.2 6.  1.8]
