In [8]:
import numpy as np
from sklearn import datasets
from sklearn.model_selection import train_test_split

In [2]:
import pandas as pd

In [3]:
num_samples = 8
sample_weights = [1/8]*num_samples
sample_weights

[0.125, 0.125, 0.125, 0.125, 0.125, 0.125, 0.125, 0.125]

In [6]:
import sys
import os

sys.path.append(os.path.join(os.path.abspath(''), ".."))
from tree.DecisionTree import DecisionTreeClassifier

In [26]:
tree = DecisionTreeClassifier(max_depth=2)

In [9]:
dataset=datasets.load_breast_cancer()
X,y=dataset.data,dataset.target
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=1234)

In [27]:
node = tree._build_decision_tree(X_train,y_train)
node

In [35]:
x_test = X_test[0:10,:]

In [25]:
%load_ext autoreload
%autoreload 2

In [32]:
from IPython.display import display

In [42]:
misclassified_idxs = []
idx = 0
for x,y in zip(X_train,y_train):
    ans = tree._traverse_decision_tree(x,node)
    if ans!=y:
        print(idx,ans,y)
        misclassified_idxs.append(idx)
        idx+=1
    else:
        idx+=1
print(misclassified_idxs)

0 0 1
2 0 1
29 0 1
39 0 1
45 0 1
75 0 1
81 0 1
85 0 1
93 0 1
95 0 1
107 0 1
125 0 1
137 0 1
157 0 1
201 0 1
202 1 0
209 0 1
253 0 1
263 0 1
272 1 0
274 0 1
327 0 1
360 0 1
369 0 1
383 0 1
405 1 0
407 0 1
410 1 0
414 0 1
419 0 1
427 0 1
435 0 1
[0, 2, 29, 39, 45, 75, 81, 85, 93, 95, 107, 125, 137, 157, 201, 202, 209, 253, 263, 272, 274, 327, 360, 369, 383, 405, 407, 410, 414, 419, 427, 435]


In [44]:
len(misclassified_idxs)

32

In [46]:
sample_weight = 1 / len(X_train)
sample_weights = [sample_weight]*len(X_train)
sample_weights = np.array(sample_weights)
total_error = np.sum(sample_weights[misclassified_idxs])
ratio = (1 - total_error) / total_error
performance_of_stump = 0.5 * np.log(ratio)

In [47]:
performance_of_stump

1.2908181381232757

In [55]:
mask = np.isin(np.arange(0,len(X_train)),misclassified_idxs)

In [66]:
len(sample_weights)

455

In [70]:
sample_weights[mask]*np.exp(performance_of_stump)

array([0.0021978, 0.0006045, 0.0021978, 0.0006045, 0.0006045, 0.0006045,
       0.0006045, 0.0006045, 0.0006045, 0.0006045, 0.0006045, 0.0006045,
       0.0006045, 0.0006045, 0.0006045, 0.0006045, 0.0006045, 0.0006045,
       0.0006045, 0.0006045, 0.0006045, 0.0006045, 0.0006045, 0.0006045,
       0.0006045, 0.0006045, 0.0006045, 0.0006045, 0.0006045, 0.0021978,
       0.0006045, 0.0006045, 0.0006045, 0.0006045, 0.0006045, 0.0006045,
       0.0006045, 0.0006045, 0.0006045, 0.0021978, 0.0006045, 0.0006045,
       0.0006045, 0.0006045, 0.0006045, 0.0021978, 0.0006045, 0.0006045,
       0.0006045, 0.0006045, 0.0006045, 0.0006045, 0.0006045, 0.0006045,
       0.0006045, 0.0006045, 0.0006045, 0.0006045, 0.0006045, 0.0006045,
       0.0006045, 0.0006045, 0.0006045, 0.0006045, 0.0006045, 0.0006045,
       0.0006045, 0.0006045, 0.0006045, 0.0006045, 0.0006045, 0.0006045,
       0.0006045, 0.0006045, 0.0006045, 0.0021978, 0.0006045, 0.0006045,
       0.0006045, 0.0006045, 0.0006045, 0.0021978, 

In [68]:
# correctly_classified_samples = X_train[~mask]
# misclassified_samples = X_train[mask]
#sample_weights[~mask]*np.exp(-performance_of_stump)
sample_weights[~mask] *= np.exp(-performance_of_stump)


TypeError: 'float' object is not subscriptable

In [71]:
sample_weights[mask] *= np.exp(performance_of_stump)

In [73]:
sample_weights /= np.sum(sample_weights)

In [83]:
bins =  np.cumsum(sample_weights)
bins = np.insert(bins,0,0)

In [101]:
import random
random_num = np.random.random_sample()
random_num

0.35364572904891045

In [108]:
bins

array([0.        , 0.015625  , 0.01680703, 0.03243203, 0.03361407,
       0.0347961 , 0.03597813, 0.03716017, 0.0383422 , 0.03952423,
       0.04070626, 0.0418883 , 0.04307033, 0.04425236, 0.0454344 ,
       0.04661643, 0.04779846, 0.0489805 , 0.05016253, 0.05134456,
       0.0525266 , 0.05370863, 0.05489066, 0.0560727 , 0.05725473,
       0.05843676, 0.05961879, 0.06080083, 0.06198286, 0.06316489,
       0.07878989, 0.07997193, 0.08115396, 0.08233599, 0.08351803,
       0.08470006, 0.08588209, 0.08706413, 0.08824616, 0.08942819,
       0.10505319, 0.10623522, 0.10741726, 0.10859929, 0.10978132,
       0.11096336, 0.12658836, 0.12777039, 0.12895242, 0.13013446,
       0.13131649, 0.13249852, 0.13368056, 0.13486259, 0.13604462,
       0.13722665, 0.13840869, 0.13959072, 0.14077275, 0.14195479,
       0.14313682, 0.14431885, 0.14550089, 0.14668292, 0.14786495,
       0.14904699, 0.15022902, 0.15141105, 0.15259309, 0.15377512,
       0.15495715, 0.15613918, 0.15732122, 0.15850325, 0.15968

In [115]:
np.digitize(0.9991,bins)

455

In [127]:
list(X_train[454])

[12.72,
 13.78,
 81.78,
 492.1,
 0.09667,
 0.08393,
 0.01288,
 0.01924,
 0.1638,
 0.061,
 0.1807,
 0.6931,
 1.34,
 13.38,
 0.006064,
 0.0118,
 0.006564,
 0.007978,
 0.01374,
 0.001392,
 13.5,
 17.48,
 88.54,
 553.7,
 0.1298,
 0.1472,
 0.05233,
 0.06343,
 0.2369,
 0.06922]

In [106]:
if random_num > bins[139] and random_num < bins[140]:
    print("True")

In [135]:
y_train

array([1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1,
       1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0,
       1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1,
       1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0,
       1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1,
       0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0,
       0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0,
       1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0,
       1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1,
       1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1,
       1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0,

In [136]:
new_X_train = []
new_y_train = []

for _ in range(len(X_train)):
    random_num = np.random.random_sample()
    idx = np.digitize(random_num,bins) - 1
    X_data = list(X_train[idx])
    y_data = y_train[idx]
    new_X_train.append(X_data)
    new_y_train.append(y_data)


In [137]:
updated_X_train = np.array(new_X_train)
updated_y_train = np.array(new_y_train)

In [3]:
from sklearn import datasets
from sklearn.model_selection import train_test_split
dataset=datasets.load_breast_cancer()
X,y=dataset.data,dataset.target
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=1234)

In [9]:
from sklearn.ensemble import AdaBoostClassifier
import numpy as np

ad = AdaBoostClassifier(n_estimators=10)
ad.fit(X_train,y_train)
res = ad.predict(X_test)
print(res)
print(y_test)
acc=np.sum(res==y_test)/len(y_test)
print(acc)

[1 1 1 1 1 1 0 1 0 0 0 1 1 1 1 0 1 1 1 0 1 0 0 0 0 1 0 1 1 1 1 1 0 1 1 1 1
 0 1 1 0 1 0 1 1 1 1 1 0 1 1 1 1 0 1 1 1 1 1 0 0 1 1 1 1 0 0 1 1 1 1 0 1 1
 1 1 1 0 1 0 1 1 1 0 0 0 0 0 1 1 1 1 1 0 0 1 1 1 1 1 0 0 1 1 0 1 1 0 0 1 0
 1 0 0]
[1 1 1 1 1 1 0 1 0 0 0 1 1 1 1 0 1 1 1 0 1 0 0 0 0 1 0 1 1 1 1 1 0 1 1 1 1
 0 0 1 0 1 0 1 1 1 1 0 0 1 1 1 1 0 0 1 1 1 1 0 1 1 1 1 1 0 0 1 1 0 1 0 1 0
 1 1 1 0 1 0 1 1 1 0 0 0 0 0 1 0 1 0 1 0 0 1 1 1 1 1 0 0 1 1 0 1 1 0 0 1 0
 1 0 0]
0.9298245614035088


In [8]:
np.log(1/0) + 0.32

ZeroDivisionError: division by zero